package it.polimi.ingsw;

public enum Label {
    ONE, TWO, AGAIN_IF_MOVE_ON_PERIMETER, IF_I_DONT_MOVE_UP,
    MOVE_OPPONENT_ON_SAME_DIRECTION, REGULAR,
    IF_I_MOVE_DOWN_TWO_LEVELS_OR_MORE, FIVE_TOWERS_COMPLETED,
    NEVER, MOVE_ON_PERIMETER, NOT_ON_SAME_CELL,
    ON_SAME_CELL_BLOCK_ONLY, NOT_ON_PERIMETER, ALWAYS, SWAP
}
